services:
  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: ppiv_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    networks:
      - ppiv_network

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: ppiv_grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - ppiv_network

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  ppiv_network:
    external: true
