# Generated by Selenium IDE
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.options import Options

class TestEditarUnidad(unittest.TestCase):
    def setUp(self):
        chrome_options = Options()
        chrome_options.add_argument("--headless")
        chrome_options.add_argument("--no-sandbox")
        chrome_options.add_argument("--disable-dev-shm-usage")
        self.driver = webdriver.Chrome(options=chrome_options)
        self.driver.implicitly_wait(10)

    def tearDown(self):
        self.driver.quit()

    def test_editarUnidad(self):
        self.driver.get("https://tpi-devops-git-main-ladyfantasys-projects.vercel.app/login")
        self.driver.set_window_size(1181, 797)
        self.driver.find_element(By.CSS_SELECTOR, ".login-input-top").click()
        self.driver.find_element(By.CSS_SELECTOR, ".login-input-top").send_keys("germangp62@gmail.com")
        self.driver.find_element(By.CSS_SELECTOR, ".login-input-bottom").send_keys("1234")
        self.driver.find_element(By.CSS_SELECTOR, ".button1").click()

        # Esperar a que cargue el AdminPanel y hacer click en "Administrar unidades"
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".admincard:nth-child(1) > .admincard__title"))
        ).click()

        # Esperar a que cargue la página Units y hacer click en la primera tarjeta de unidad
        WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".unit-card"))
        ).click()

        # Esperar a que cargue la página de detalle de unidad y el campo title esté presente
        WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.NAME, "title"))
        )

        # Editar el título
        title_field = self.driver.find_element(By.NAME, "title")
        title_field.clear()
        title_field.send_keys("Unidad Editada")

        # Guardar los cambios
        button = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".unit-detail__buttons > .button1"))
        )
        self.driver.execute_script("arguments[0].scrollIntoView(true);", button)
        self.driver.execute_script("arguments[0].click();", button)

        # Verificar que se redirija a la página de unidades o se muestre un mensaje de éxito
        try:
            # Esperar a que se redirija a la página de unidades
            WebDriverWait(self.driver, 10).until(
                lambda driver: "units" in driver.current_url
            )
            self.assertTrue(True, "Se redirigió correctamente a la página de unidades")
        except:
            # Si no se redirige, verificar que se muestre un mensaje de éxito
            try:
                WebDriverWait(self.driver, 5).until(
                    EC.presence_of_element_located((By.CSS_SELECTOR, ".success-message, .alert-success"))
                )
                self.assertTrue(True, "Se mostró un mensaje de éxito")
            except:
                # Como último recurso, verificar que el título se haya actualizado
                title_field = self.driver.find_element(By.NAME, "title")
                self.assertEqual(title_field.get_attribute("value"), "Unidad Editada", "El título debería haberse actualizado")
  
