global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # PPIV Backend
  - job_name: "ppiv-backend"
    static_configs:
      - targets: ["backend:5000"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  # PPIV Frontend
  - job_name: "ppiv-frontend"
    static_configs:
      - targets: ["frontend:80"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  # MySQL Exporter
  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]

  # Node Exporter (if running on hosts)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Docker containers
  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 30s
