global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # PPIV Backend
  - job_name: "ppiv-backend"
    static_configs:
      - targets: ["ppiv_backend_dev:5000"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  # PPIV Frontend
  - job_name: "ppiv-frontend"
    static_configs:
      - targets: ["ppiv_frontend_dev:3000"]
    metrics_path: "/metrics"
    scrape_interval: 10s
